name: update-blacklist
run-name: ${{ github.actor }} - updating blacklist
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'
jobs:
  RunBlockListUpdateScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create new branch
        run: git checkout -b update-blacklist-action
      - name: Run a one-line script
        run: ./blocklists-dl.sh
      - name: set github username
        run: git config user.name github-actions
      - name: set github email
        run: git config user.email github-actions@github.com
      - name: check for changes
        run: git status
      - name: Pull
        run: git pull
      - name: stage changed files
        run: git add mikrotik-blacklist.rsc
      - name: commit changed files
        run: git commit -m "Auto updating mikrotik-blacklist.rsc"
      - name: push code to update-blacklist-action
        run: git push origin HEAD:update-blacklist-action
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto updating mikrotik-blacklist.rsc
          title: 'Blacklist update'
          body: >
            This PR was auto-generated
